# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=35)),
                ('complemento', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=25)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('FoneResidencial', models.CharField(max_length=15)),
                ('FoneTrabalho', models.CharField(max_length=15)),
                ('RendaFamiliar', models.DecimalField(decimal_places=2, max_digits=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cnpj', models.CharField(max_length=20)),
                ('Nome', models.CharField(max_length=30)),
                ('Endereco', models.CharField(max_length=35)),
                ('Complemento', models.CharField(max_length=50)),
                ('Cidade', models.CharField(max_length=25)),
                ('Estado', models.CharField(max_length=2)),
                ('Cep', models.CharField(max_length=8)),
                ('Fone', models.CharField(max_length=15)),
                ('Responsavel', models.CharField(max_length=30)),
                ('Website', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoPedido', models.IntegerField()),
                ('CodigoProduto', models.IntegerField()),
                ('PrecoUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrecoUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('Codigo', models.AutoField(primary_key=True, serialize=False)),
                ('DataPedido', models.DateField()),
                ('DataRecebimento', models.DateField()),
                ('PrecoTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CodigoFornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoProduto', models.IntegerField()),
                ('NomeProduto', models.CharField(max_length=35)),
                ('Quantidade', models.IntegerField()),
                ('MinQuantidade', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('CodigoVenda', models.AutoField(primary_key=True, serialize=False)),
                ('DataVenda', models.DateField()),
                ('ValorTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CodigoCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='CodigoProduto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produto'),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='CodigoVenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Venda'),
        ),
    ]
