# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='CodigoProduto',
        ),
        migrations.AlterField(
            model_name='venda',
            name='CodigoCliente',
            field=models.CharField(max_length=14),
        ),
    ]
