# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170422_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='CodigoVenda',
        ),
    ]
