# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170422_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='CodigoProduto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='CodigoVenda',
            field=models.IntegerField(default=0),
        ),
    ]
